apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db-deploy
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: postgres:13-alpine
        name: postgres-container
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {} 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis-deploy
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:7.0-alpine
        name: redis-container
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - name: redis-data
        emptyDir: {} 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result-deploy
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: henrykum23/result:latest
        name: result-container
        ports:
        - containerPort: 80
          name: result

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote-deploy
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: henrykum23/vote:latest
        name: vote-container
        ports:
        - containerPort: 80
          name: vote

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker-deploy
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: henrykum23/worker:latest
        name: worker-container

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db-svc
  namespace: argocd
spec:
  type: ClusterIP
  ports:
  - name: "db-service"
    port: 5432
    targetPort: 5432
  selector:
    app: db
  
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-svc
  namespace: argocd
spec:
  type: ClusterIP
  ports:
  - name: "redis-service"
    port: 6379
    targetPort: 6379
  selector:
    app: redis
  
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result-svc
  namespace: argocd
spec:
  type: NodePort
  ports:
  - name: "result-service"
    port: 5003
    targetPort: 80
    nodePort: 31003
  selector:
    app: result

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote-svc
  namespace: argocd
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: 5004
    targetPort: 80
    nodePort: 31004
  selector:
    app: vote
