apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-deployment
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      name: netflix
  template:
    metadata:
      labels:
        name: netflix
    spec:
      containers:
        - name: netflix-container
          image: chriscloudaz/netflix
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-service
  namespace: argocd
spec:
  type: NodePort
  selector:
    name: netflix
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 80
      nodePort: 31010